[package]
rust-version.workspace = true
name = "sdkwork-api-manager-assembly"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "Generated API assembly for sdkwork-manager application HTTP plane."


[lints]
workspace = true
[lib]
name = "sdkwork_api_manager_assembly"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
tokio.workspace = true
sdkwork-web-bootstrap.workspace = true
sdkwork-web-core.workspace = true
sdkwork-database-sqlx.workspace = true
sdkwork_manager_service_host.workspace = true
sdkwork-routes-manager-app-api.workspace = true
sdkwork-routes-manager-backend-api.workspace = true
