[package]
rust-version.workspace = true
name = "sdkwork-api-manager-standalone-gateway"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true


[[bin]]
name = "manager-server"
path = "src/main.rs"


[lints]
workspace = true
[dependencies]
sdkwork_api_manager_assembly.workspace = true
sdkwork_api_iam_assembly.workspace = true
sdkwork_api_drive_assembly.workspace = true
sdkwork_api_order_assembly.workspace = true
sdkwork_api_promotion_assembly.workspace = true
sdkwork_api_payment_assembly.workspace = true
sdkwork_api_membership_assembly.workspace = true
axum = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde_json = { workspace = true }
sdkwork-web-bootstrap = { workspace = true }
sdkwork-web-core = { workspace = true }
sdkwork-iam-web-adapter = { workspace = true }
sdkwork-database-sqlx.workspace = true
